# Generated by Django 3.1.4 on 2022-02-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-datetime']},
        ),
        migrations.AddField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
