# Generated by Django 3.1.4 on 2022-02-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0002_auto_20220201_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
    ]
