# Generated by Django 3.1.4 on 2022-02-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0003_remove_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='s', max_length=2),
        ),
    ]
